### ISSUE TITLE
Path Output File is absolute

### ISSUE THREAD

**Issue by riccardotommasini** [RMLio/rmlmapper-java#183] opened 2022-07-20 07:16 UTC
I just noticed that the explanation for the -o/--outputfile does not explicitly indicate that the path should be absolute.

**Comment by bjdmeest** [comment] 2022-07-27 08:55
Hmmm, this is in fact a regression since v6, relative paths should in fact work, but we started testing whether we could actually write to the output before start to avoid that we "generate 100M triples and then see we can't write to output and the output is lost forever". In fact. if you prepend your outputfile with `./`, the current release should work.
In any case , a fix is in the making :)

**Comment by DylanVanAssche** [comment] 2023-01-25 08:08
This is fixed in a newer release, closing.

**Closed by DylanVanAssche** 2023-01-25 08:08 UTC
Labels: bug, next release
