### ISSUE TITLE
Error when there is no rr:TriplesMap

### ISSUE THREAD

**Issue by ktk** [RMLio/rmlmapper-java#98] opened 2021-02-20 15:53 UTC
When there is no `rr:TriplesMap` defined in the mapping file I get an error like this:

```
22:41:14.251 [main] ERROR be.ugent.rml.cli.Main               .main(193) - Failed to make mapping file conformant to RML spec.
java.lang.Exception: Mapping requires at least one TriplesMap
        at be.ugent.rml.conformer.MappingConformer.detect(MappingConformer.java:80)
        at be.ugent.rml.conformer.MappingConformer.conform(MappingConformer.java:55)
        at be.ugent.rml.cli.Main.main(Main.java:187)
        at be.ugent.rml.cli.Main.main(Main.java:36)
```

But the XML example [in the spec](https://rml.io/specs/rml/#mapping-logical-sources) do not provide one either. So who is correct, spec or implementation?

**Comment by thomas-delva** [comment] 2021-02-22 11:10
Hi and thanks for using RML,

Indeed, this (non-fatal) error does not align perfectly with the examples in the spec. However, for the spec's examples the implementation can infer what the triples maps are (namely: the subjects of `rml:logicalSource`) and the output is as intended even without explicitly using stating `a rr:TriplesMap`.

We are adding `a rr:TriplesMap` statements to the examples in the spec to make it more clear for everyone.

**Comment by DylanVanAssche** [comment] 2021-03-23 08:11
This is now fixed on https://rml.io/rml/spec. 
Let us know if you still have issues.

**Closed** 2021-04-20 08:49 UTC
Labels: bug, more-information-needed
