### ISSUE TITLE
Class Not Found: org.rdfhdt.hdt.options.HDTOptions error in the readmetest.java class

### ISSUE THREAD

**Issue by mrtylmz** [RMLio/rmlmapper-java#207] opened 2023-06-08 17:25 UTC
Hi,
I have added the latest version as of now for rmlmapper-java maven dependency into my project
```
<dependency>
				<groupId> be.ugent.rml </groupId>
				<artifactId>rmlmapper</artifactId>
				<version>6.1.3</version>
			</dependency>
```

And followed the readme example here - https://github.com/RMLio/rmlmapper-java/blob/master/src/test/java/be/ugent/rml/readme/ReadmeTest.java

When I run this code I am getting following error  
"java.lang.ClassNotFoundException: org.rdfhdt.hdt.options.HDTOptions"

Any idea?
Thank you!

**Comment by bjdmeest** [comment] 2023-06-09 07:57
Hi,

My first guess would be that the HDT dependency isn't properly found, can
you try with including the jitpack repo, cfr
https://github.com/RMLio/rmlmapper-java/blob/15c9c02c78aa743df02f7e773c2b1a229c3bc377/pom.xml#L56
?

Op do 8 jun. 2023 19:26 schreef MURAT YILMAZ ***@***.***>:

**Comment by mrtylmz** [comment] 2023-06-09 14:32
Thanks for suggestion @bjdmeest . But it did not work out. I think I need to add associated dependency for HDTOptions , but I 'd assume once I have added rmlmapper all necessary dependencies are loaded.

**Comment by mrtylmz** [comment] 2023-06-29 20:42
> Did adding the dependency to your pom.xml work for you?

unfortunately no

**Comment by DylanVanAssche** [comment] 2023-09-15 07:37
Probably fixed with b89d5725ce9ea32a2739cfeb52de201578ecff62
Can you maybe verify by using the `development`  branch?

**Comment by philharveyonline** [comment] 2023-09-26 09:25
I've got the same problem.

I believe the root cause is that rmlmapper:v6.1.3 depends on com.github.rdfhdt:hdt-java:v3.0.5 but hdt-java:v3.0.5 is not in Maven's default repository at maven.org. The [latest version there is v2.1.2](https://mvnrepository.com/artifact/be.ugent.rml/rmlmapper/6.1.3#:~:text=github.rdfhdt%20%C2%BB-,hdt%2Djava,-v3.0.5).

Unfortunately I work in a tightly controlled organization where we can only use dependencies from maven.org, spring.io and google.com (we have to request that the dependencies are copied to our internal mirror).

So your workaround to use jitpack won't work for me.

Would it be possible for you to change your dependencies such that they're all available in maven.org? I'd be happy to help if you think this is feasible.

**Comment by DylanVanAssche** [comment] 2023-09-26 11:53
> I believe the root cause is that rmlmapper:v6.1.3 depends on com.github.rdfhdt:hdt-java:v3.0.5 but hdt-java:v3.0.5 is not in Maven's default repository at maven.org. The [latest version there is v2.1.2](https://mvnrepository.com/artifact/be.ugent.rml/rmlmapper/6.1.3#:~:text=github.rdfhdt%20%C2%BB-,hdt%2Djava,-v3.0.5).

It is solved in development, no release yet.

> Unfortunately I work in a tightly controlled organization where we can only use dependencies from maven.org, spring.io and google.com (we have to request that the dependencies are copied to our internal mirror).

RMLMapper has more dependencies coming from jitpack.

> Would it be possible for you to change your dependencies such that they're all available in maven.org? I'd be happy to help if you think this is feasible.

Would require to upload these packages to maven.org, maintain them and patch the RMLMapper to use the Maven ones.
The ones that are not on Maven are also for example the FnO ones which we maintain at https://github.com/fnoio. We might upload them to Maven in the future, however we are at limited capacity as this is a resource for our research which we maintain already for a long time. Feel free to send us an e-mail at info@rml.io to discuss opportunities here. RDFHDT is not maintained by us, you will have to convince the RDFHDT maintainers to upload their packages to Maven.

**Closed** 2023-10-05 13:08 UTC
Labels: bug, next release, more-information-needed
