### ISSUE TITLE
Why <#NameOfMapping> does not work with RMLMapper jar?

### ISSUE THREAD

**Issue by paulakeen** [RMLio/rmlmapper-java#96] opened 2021-02-17 15:43 UTC
I'm tryin to merge two different CSV into one single RDF using the RMLMapper jar...looking into the documentation of the RML.io specification I found the section 9. Integrated Mapping, but the examples therein are not working with the RMLMapper....apparently the it doesn't like the '<#AirportMapping>' syntax before the rml:logicalsource...

Do you have any example using :TriplesMap?

This works for me with one single CSV:

:TriplesMap a rr:TriplesMap;
  rml:logicalSource [
    rml:source [
      a csvw:Table;
      csvw:url "edw.sl_vw_oper_prod.csv";
      csvw:dialect [ 
        a csvw:Dialect;
        csvw:delimiter ";"
      ]
    ];
    rml:referenceFormulation ql:CSV
  ].

**Comment by DylanVanAssche** [comment] 2021-02-18 07:21
Hi!

It seems that there's a small mistake in the examples:

```
<#AirportMapping>
  rml:logicalSource [
    rml:source "Airport.csv" ;
    rml:referenceFormulation ql:CSV
  ];
```

`<#AirportMapping>` is not specified as a `rr:TriplesMap`, this can be fixed like this:

```
<#AirportMapping> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "Airport.csv" ;
    rml:referenceFormulation ql:CSV
  ];
```

We will update the examples to fix this.

**Comment by bjdmeest** [comment] 2021-02-18 07:39
Duplicate of #91

**Comment by DylanVanAssche** [comment] 2021-03-23 08:08
This is now fixed on https://rml.io/rml/spec.
Feel free to try it out!

**Closed** 2021-04-15 07:13 UTC
Labels: bug, more-information-needed
