### ISSUE TITLE
support rr:logicalTable, rr:sqlVersion

### ISSUE THREAD

**Issue by VladimirAlexiev** [RMLio/rmlmapper-java#62] opened 2020-06-22 15:48 UTC
(Sorry, I wanted to post this against https://rml.io/specs/rml/ but I can't find the repo).

Since RML extends R2RML, I think that each R2RML file should be a valid RML file.

With this objective in mind, please allow `rr:logicalTable` to mean the same as `rml:logicalSource` (for the case of RDB sources).
Less importantly, allow `rr:sqlVersion` to mean the same as `rml:referenceFormulation`.

By "mean the same" I mean:
- demand in the spec that they should be supported by any implementation
- perhaps declare them as subprops of the `rml:` props

- https://github.com/RMLio/ANYtoRML/blob/master/R2RMLtoRML.py#L30 makes such replacements
- rmlmapper-java says that it converts R2RML on the fly to RML but I think that concerns only the database connection options?

I think there is a lot of value if unchanged R2RML files can be run through RML, and to demand the same of other RML implementations.

**Comment by thomas-delva** [comment] 2021-04-13 08:12
Note: this causes test case [RMLTC0011a](https://rml.io/test-cases/#rmltc0011a-postgresql) to fail with the RMLMapper, since it uses `rr:logicalTable`

**Comment by DylanVanAssche** [comment] 2021-05-05 13:03
@thomas-delva @VladimirAlexiev 

> rmlmapper-java says that it converts R2RML on the fly to RML but I think that concerns only the database connection options?

The RMLMapper should now better support R2RML with the newest v4.10.0 release.
Please let us know if this part of the issue is fixed with the latest release :)

**Closed** 2021-11-04 08:56 UTC
Labels: enhancement, more-information-needed
